Bugfix/tsk 197
wildflower-keeper/frontend pull request #52
Opened 2024-09-27 11:54 UTC by imfreeman1

## What is this PR🔍?

- [x] 새로운 기능 추가
- [x] 버그 수정

## - ISSUE #51 

## Changes📃
 - filterType === 'NAME' && !filterValue 일 때 submit 버튼이 작동하지 않도록 변경
 - useSearch hook을 만들어 로직 분리

## Screenshot📸

|기능|스크린샷|
|---|---|
|||

2024-09-27 13:53 UTC, eomsteve requested changes

2024-09-27 13:53 UTC, eomsteve commented on src/components/Composition/SearchBar/hook.tsx
hook이라는  네이밍은 약간 함수를 function 이라고 짓는것같아서 지양하는게 나을것 같습니다. useSearch라고 하면 아 저게 훅이구나 알수 있을것 같아요

2024-09-27 13:53 UTC, eomsteve commented on src/components/Composition/SearchBar/hook.tsx
> +  const isSubmitDisabled = useMemo(() => {
isSubmitDisabled 에 useMemo를 쓴 이유가 무엇일까요?

2024-09-27 13:53 UTC, eomsteve commented on src/components/Composition/SearchBar/index.tsx
> +  paramHandler: (filters: FilterValuesType, page: number) => void;
함수를 인자로 받는 부분에서 위화감이 느껴져 해당 컴포넌트를 쓰는 상위 파일을 보고 왔는데, 필터가 바뀌면 setParam이 호출되고, 아래에 buttonConatiner도 param과 setParam이 바뀌고 그럼 부모 컴포넌트로 파생되어 리 랜더링이 일어나고 순서는 모호해진 채로 부모와 자식컴포넌트가 전부 리랜더링 될것이고..  filterValue를 굳이 또 선언해서 사용할 필요가 없어보입니다 props드릴링으로 코드가 더 지저분해 지고 파생효과가 너무 많아서 추적이 어려워질 것같아요

1. 차라리 param, setParam, useQuery를 훅으로 만들어 이곳저곳에서 재활용한다.
2. useContext를 사용하는 논리 로직을 다시 생각해본다
3. 2와 마찬가지로 zustand로 전역상태관리를 한다.

이정도가 있을것 같습니당

2024-09-27 14:53 UTC, imfreeman1 commented on src/components/Composition/SearchBar/hook.tsx
리뷰 감사합니다!  파일 내에서만 사용된다고 생각했기 때문에 hook이라고 작성하게 되었습니다. 리뷰 내용을 반영하여 수정하겠습니다!

2024-09-27 14:57 UTC, imfreeman1 commented on src/components/Composition/SearchBar/hook.tsx
> +  const isSubmitDisabled = useMemo(() => {
작성할 당시 해당 isSubmitDisabled가 계산이 들어간다고 생각하여 useMemo를 사용하였습니다. 리뷰를 보고 다시 보니 isSubmitDisabled는 간단한 계산식이고, 오히려 메모이제이션 할 경우 낭비가 발생한다는 것을 알게 되었습니다! 리뷰 반영하여 수정하도록 하겠습니다

2024-09-27 15:05 UTC, imfreeman1 commented on src/components/Composition/SearchBar/index.tsx
> +  paramHandler: (filters: FilterValuesType, page: number) => void;
좋은 지적 감사합니다! 수정하도록 하겠습니다!

2024-09-28 13:47 UTC, eomsteve commented on src/components/Layout/UserBoardContainer/index.tsx
handleSubmit함수가 실행되면 이 페이지가 전부 리 랜더링 될것이고 useQuery가 재선언 재 할당 되면서 queryFn이 실행되면서 바뀐 param으로 데이터를 불러와 최신화 한다 가 원하는 로직인가요?

2024-09-29 01:44 UTC, imfreeman1 commented on src/components/Layout/UserBoardContainer/index.tsx
네 말씀하신 로직으로 최신화를 하고자 하였습니다! 
리뷰 남겨주신 내용 코드를 보니 queryKey가 useMemo로 관리될 필요가 없어보입니다. 이것 수정해서 PR 올릴까요??

2024-09-29 02:18 UTC, eomsteve commented on src/components/Layout/UserBoardContainer/index.tsx
괜찮을거같아요, 여유되면 infinite Query쪽도 참고해서 개발하면 좋아보이긴 합니다. Approve

2024-09-29 02:19 UTC, eomsteve approved these changes

2024-09-29 02:26 UTC, imfreeman1 commented on src/components/Layout/UserBoardContainer/index.tsx
넵 확인했습니다!

2024-09-29 03:05 UTC, merged