Feature/tsk 230 사용자의 재실, 외출 상태 변경
wildflower-keeper/frontend pull request #56
Opened 2024-10-31 14:47 UTC by dong1hyun

## What is this PR🔍?

- [x] 새로운 기능 추가
- [x] CSS 등 사용자 UI 디자인 변경

## - ISSUE 

## Changes📃
- 사용자의 재실, 외출 상태 변경

## Screenshot📸

|기능|스크린샷|
|---|---|
||![image](https://github.com/user-attachments/assets/8c2b037e-0403-4107-88b8-8f7b06a1c788)|

2024-10-31 14:51 UTC, dong1hyun commented on src/components/List/UserBoard/items/StatusToggle.tsx
> +                await new Promise(resolve => setTimeout(resolve, 1000));
진욱님이 고의적인 시간지연이 필요하다고 하셔서 넣었습니다.

2024-11-03 13:40 UTC, eomsteve requested changes

2024-11-03 13:40 UTC, eomsteve commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "src/components/Composition/Loading"],
이걸 추가하신 이유가 있을까요 ts, tsx파일이라면 전부 타입 검사에 include되어있는데

2024-11-03 13:40 UTC, eomsteve commented on src/components/List/UserBoard/items/StatusToggle.tsx
> +                isOpenStatus &&
삼항연산자가 반복되고 하나의 컴포넌트 파일에서 여러가지 state를 이용하는건 코드를 복잡하게 만드는 원인이 될 수 있습니다 어떤 버튼을 눌렀을때 어떤 함수가 호출되야 하는지, 어떤 데이터가 변경돠야하는지 분리할수 있는 부분이 무엇인지 고민해보면 좋을 것 같습니다

지금 보면 StatusToggle이 컴포넌트는 StatusToggleOpenAndHandleStatusToggle이란 이름이 어울리는 컴포넌트 같습니다

2024-11-03 13:40 UTC, eomsteve commented on src/components/List/UserBoard/items/StatusToggle.tsx
> +                await new Promise(resolve => setTimeout(resolve, 1000));
음.. 정확한 이유는 모르신걸까용??

2024-11-03 13:40 UTC, eomsteve commented on src/components/List/UserBoard/items/StatusToggle.tsx
> +        setLoadingStatus(index);
loading 상태는 mutate가 가지고 있을겁니다 이걸한번 이용해 보시는게 좋을 것 같아요

2024-11-03 13:54 UTC, dong1hyun commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "src/components/Composition/Loading"],
아 이게 아마 자동으로 생성된거 같은데 제가 확인을 못했네요 수정하겠습니다.

2024-11-03 13:56 UTC, dong1hyun commented on src/components/List/UserBoard/items/StatusToggle.tsx
> +                await new Promise(resolve => setTimeout(resolve, 1000));
노션 태그 변경할 때처럼 만들기 위해서라고 하셨습니다.

2024-11-03 14:49 UTC, dong1hyun commented on src/components/List/UserBoard/items/StatusToggle.tsx
> +                isOpenStatus &&
그러네요 제가 봐도 가독성도 떨어지고 한 컴포넌트에서 두 가지 일을 하는 느낌이 드네요. 수정하겠습니다.

2024-11-03 23:33 UTC, eomsteve approved these changes

2024-11-04 05:27 UTC, merged