Feature/tsk 240  2차 인증 구현
wildflower-keeper/frontend pull request #57
Opened 2024-11-01 15:24 UTC by dong1hyun

## What is this PR🔍?

- [x] 새로운 기능 추가

## - ISSUE 

## Changes📃
- 2차 인증 구현

## Screenshot📸

|기능|스크린샷|
|---|---|
||![image](https://github.com/user-attachments/assets/c40fca40-4aa7-4bdc-9eae-92cec1e43c30)|

2024-11-01 15:25 UTC, dong1hyun commented on src/components/Layout/AuthProvider/index.tsx
1차 인증 성공 여부와, 현재 인증을 시도하는 admin id를 저장하기 위해 context api 사용

2024-11-03 13:25 UTC, eomsteve requested changes

2024-11-03 13:25 UTC, eomsteve commented on src/api/v1/shelter-admin/index.ts
> +    if(!data) { // 입력 데이터가 부족할 경우
얼리리턴으로 한번 다시 리팩터링 하는게 좋아보입니다. 에러 로직을 모은다던가 코드를 읽기에 elseif문은 이전의 context를 알고 읽어야 하는 피로감 때문에 가능하다면 저는 if문만으로 구성하는걸 선호합니다

2024-11-03 13:25 UTC, eomsteve commented on src/app/(beforeLogin)/auth/page.tsx
> +        {true ? <FirstAuth />
이로직은 무엇일까요..?

2024-11-03 13:25 UTC, eomsteve commented on src/components/Layout/FirstAuth/index.tsx
> +        console.log(res);
콘솔은 항상 푸시하기전에 삭제하는게 좋습니다

2024-11-03 13:25 UTC, eomsteve commented on src/components/Layout/FirstAuth/index.tsx
> +    setAuthLoading(true);
tanstack query 에서는 비동기 상태관리에 대한 상태값을 기본적으로 제어할수 있게 라이브러리에서 제공하고 있습니다. setAuthLoading을 사용하기 보단 mutate에서 관리하는게 나아보입니다

2024-11-03 13:25 UTC, eomsteve commented on src/api/v1/shelter-admin/index.ts
> +export function first_auth(loginData: LoginBodyType): Promise<LoginSuccessType> {
코드 컨벤션 상 CamleCase를사용하고 있었는데, snake case를 사용하는건 지양하는게 좋습니다.

2024-11-03 14:52 UTC, dong1hyun commented on src/api/v1/shelter-admin/index.ts
> +export function first_auth(loginData: LoginBodyType): Promise<LoginSuccessType> {
수정하겠습니다.

2024-11-03 15:01 UTC, dong1hyun commented on src/api/v1/shelter-admin/index.ts
> +    if(!data) { // 입력 데이터가 부족할 경우
아하 이해했습니다 수정하겠습니다.

2024-11-03 15:07 UTC, dong1hyun commented on src/app/(beforeLogin)/auth/page.tsx
> +        {true ? <FirstAuth />
앗 이건 두 번째 커밋에서는 수정된 내용입니다.

2024-11-03 15:07 UTC, dong1hyun commented on src/components/Layout/FirstAuth/index.tsx
> +        console.log(res);
이것도 두 번째 커밋에서는 수정된 내용입니다.

2024-11-03 23:33 UTC, eomsteve requested changes

2024-11-03 23:33 UTC, eomsteve commented on src/api/v1/shelter-admin/index.ts
> +    if ("authToken" in data && "expiredAt" in data) return data;
보통, 잘되는 케이스를 가장 마지막에 두고, 에러를 위로 올려서 걸러내는 방식으로 쓰는게 논리상 맞는것같아요

2024-11-03 23:33 UTC, eomsteve commented on src/components/Layout/SecondAuth/index.tsx
> +                window.location.href = "/dashboard";
Nextjs나 react 를 쓸 경우에는 window를 이용한 네이게이션은 좋지않습니다

2024-11-04 02:43 UTC, merged