Feature/spt 28 일반 관리자 생성
wildflower-keeper/frontend pull request #63
Opened 2024-11-18 14:32 UTC by dong1hyun

## What is this PR🔍?

- [x] 새로운 기능 추가
- [x] CSS 등 사용자 UI 디자인 변경
- [x] 파일 혹은 폴더 삭제

## - ISSUE 

## Changes📃

## Screenshot📸

|기능|스크린샷|
|---|---|
||![image](https://github.com/user-attachments/assets/d0019e6c-17c6-4d5c-981b-20d52cd450b6)|

2024-11-18 14:36 UTC, dong1hyun commented on src/components/Layout/FirstAuth/index.tsx
이 아래부터는 이메일 로그인 관련(SPT-27) 코드입니다

2024-11-18 23:33 UTC, hokidoki requested changes
p1 : 관리자 생성 페이지의 경우 일반 관리자의 경우 이 페이지에 접근 하면 안됩니다. 혹시 관련코드가 어디 있을까요 ? 

p1 : v2라우트가 발생하였으니 이에 맞게 폴더 컨벤션 맞춰주세요

2024-11-18 23:33 UTC, hokidoki commented on src/api/utils.const.ts
> +  join(["api", version, path], "/");
p1 : src/api/v2 폴더를 만들어 폴더 컨벤션을 유지해주세요.

2024-11-18 23:33 UTC, hokidoki commented on src/api/v1/shelter-admin/Routes.const.ts
> +export const CREATE_ADMIN_ACCOUNT = generatePathByBase(V2_BASE_PATH, "shelter-account");
p1 : src/api/v2/shelter-admin 폴더를 만들어 폴더 컨벤션을 유지해주세요.

2024-11-18 23:33 UTC, hokidoki commented on src/api/v1/shelter-admin/index.ts
p1 : 리턴 타입을 명시해주세요

2024-11-19 03:17 UTC, dong1hyun commented on src/api/utils.const.ts
> +  join(["api", version, path], "/");
이 파일은 v1폴더 내부가 아닌 api폴더에 있는 파일인데 genreateBasePath_v2의 위치를 변경해야 하나요?

2024-11-21 06:00 UTC, dong1hyun commented on src/api/v2/shelter-admin/index.ts
> +        });
일반 관리자가 관리자 리스트로 접속하면 error 페이지로 이동시켜서 버튼을 통한 관리자 추가 페이지로 이동은 막아놨고, 혹여나 url로 관리자 추가 페이지로 이동하더라도 관리자 추가를 했을 때 에러와 함께 메시지를 보여주고 있습니다.

2024-11-21 13:23 UTC, hokidoki approved these changes

2024-11-21 13:43 UTC, merged